import SkillImageModel from '../models/SkillImageModel'

const images: SkillImageModel[] =
[
    {
        id:'1',
        level: 2,
        type: 'AirMagic',
        url:'AirMagicAdvanced.jpg',
        title:'123',
        width:'',
    },
    {
        id:'2',
        level: 1,
        type: 'AirMagic',
        url:'AirMagicBasic.jpg',
        title:'1234',
        width:'',
    },
    {
        id:'3',
        level: 3,
        type: 'AirMagic',
        url:'AirMagicExpert.jpg',
        title:'12345',
        width:'',
    },
    {
        id:'4',
        level: 2,
        type: 'arch',
        url:'ArcheryAdvanced.jpg',
        title:'12',
        width:'',
    },
    {
        id:'5',
        level: 1,
        type: 'arch',
        url:'ArcheryBasic.jpg',
        title:'21',
        width:'',
    },
    {
        id:'6',
        level: 3,
        type: 'arch',
        url:'ArcheryExpert.jpg',
        title:'31',
        width:'',
    },
    {
        id:'7',
        level: 2,
        type: 'arm',
        url:'ArmorerAdvanced.jpg',
        title:'13',
        width:'',
    },
    {
        id:'8',
        level: 1,
        type: 'arm',
        url:'ArmorerBasic.jpg',
        title:'34',
        width:'',
    },
    {
        id:'9',
        level: 3,
        type: 'arm',
        url:'ArmorerExpert.jpg',
        title:'43',
        width:'',
    },
    {
        id:'10',
        level: 2,
        type: 'art',
        url:'ArtilleryAdvanced.jpg',
        title:'56',
        width:'',
    },
    {
        id:'11',
        level: 1,
        type: 'art',
        url:'ArtilleryBasic.jpg',
        title:'65',
        width:'',
    },
    {
        id:'12',
        level: 3,
        type: 'art',
        url:'ArtilleryExpert.jpg',
        title:'55',
        width:'',
    },
    {
        id:'13',
        level: 2,
        type: 'bal',
        url:'BallisticsAdvanced.jpg',
        title:'66',
        width:'',
    },
    {
        id:'14',
        level: 1,
        type: 'bal',
        url:'BallisticsBasic.jpg',
        title:'67',
        width:'',
    },
    {
        id:'15',
        level: 3,
        type: 'bal',
        url:'BallisticsExpert.jpg',
        title:'76',
        width:'',
    },
    {
        id:'16',
        level: 2,
        type: 'dip',
        url:'DiplomacyAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'17',
        level: 1,
        type: 'dip',
        url:'DiplomacyBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'18',
        level: 3,
        type: 'dip',
        url:'DiplomacyExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'19',
        level: 2,
        type: 'eag',
        url:'EagleEyeAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'20',
        level: 1,
        type: 'eag',
        url:'EagleEyeBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'21',
        level: 3,
        type: 'eag',
        url:'EagleEyeExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'22',
        level: 2,
        type: 'ear',
        url:'EarthMagicAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'23',
        level: 1,
        type: 'ear',
        url:'EarthMagicBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'24',
        level: 3,
        type: 'ear',
        url:'EarthMagicExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'25',
        level: 2,
        type: 'est',
        url:'EstatesAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'26',
        level: 1,
        type: 'est',
        url:'EstatesBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'27',
        level: 3,
        type: 'est',
        url:'EstatesExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'28',
        level: 2,
        type: 'fir',
        url:'FireMagicAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'29',
        level: 1,
        type: 'fir',
        url:'FireMagicBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'30',
        level: 3,
        type: 'fir',
        url:'FireMagicExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'31',
        level: 2,
        type: 'fai',
        url:'FirstAidAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'32',
        level: 1,
        type: 'fai',
        url:'FirstAidBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'33',
        level: 3,
        type: 'fai',
        url:'FirstAidExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'34',
        level: 2,
        type: 'int',
        url:'IntelligenceAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'35',
        level: 1,
        type: 'int',
        url:'IntelligenceBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'36',
        level: 3,
        type: 'int',
        url:'IntelligenceExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'37',
        level: 2,
        type: 'lea',
        url:'LeadershipAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'38',
        level: 1,
        type: 'lea',
        url:'LeadershipBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'39',
        level: 3,
        type: 'lea',
        url:'LeadershipExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'40',
        level: 2,
        type: 'ler',
        url:'LearningAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'41',
        level: 1,
        type: 'ler',
        url:'LearningBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'42',
        level: 3,
        type: 'ler',
        url:'LearningExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'43',
        level: 2,
        type: 'Logistics',
        url:'LogisticsAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'44',
        level: 1,
        type: 'Logistics',
        url:'LogisticsBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'45',
        level: 3,
        type: 'Logistics',
        url:'LogisticsExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'46',
        level: 2,
        type: 'Luck',
        url:'LuckAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'47',
        level: 1,
        type: 'Luck',
        url:'LuckBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'48',
        level: 3,
        type: 'Luck',
        url:'LuckExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'49',
        level: 2,
        type: 'Mysticism',
        url:'MysticismAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'50',
        level: 1,
        type: 'Mysticism',
        url:'MysticismBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'51',
        level: 3,
        type: 'Mysticism',
        url:'MysticismExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'52',
        level: 2,
        type: 'Navigation',
        url:'NavigationAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'53',
        level: 1,
        type: 'Navigation',
        url:'NavigationBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'54',
        level: 3,
        type: 'Navigation',
        url:'NavigationExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'55',
        level: 2,
        type: 'Necromancy',
        url:'NecromancyAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'56',
        level: 1,
        type: 'Necromancy',
        url:'NecromancyBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'57',
        level: 3,
        type: 'Necromancy',
        url:'NecromancyExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'58',
        level: 2,
        type: 'Offense',
        url:'OffenseAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'59',
        level: 1,
        type: 'Offense',
        url:'OffenseBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'60',
        level: 3,
        type: 'Offense',
        url:'OffenseExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'61',
        level: 2,
        type: 'Pathfinding',
        url:'PathfindingAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'62',
        level: 1,
        type: 'Pathfinding',
        url:'PathfindingBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'63',
        level: 3,
        type: 'Pathfinding',
        url:'PathfindingExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'64',
        level: 2,
        type: 'Resistance',
        url:'ResistanceAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'65',
        level: 1,
        type: 'Resistance',
        url:'ResistanceBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'66',
        level: 3,
        type: 'Resistance',
        url:'ResistanceExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'67',
        level: 2,
        type: 'Scouting',
        url:'ScoutingAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'68',
        level: 1,
        type: 'Scouting',
        url:'ScoutingBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'69',
        level: 3,
        type: 'Scouting',
        url:'ScoutingExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'70',
        level: 2,
        type: 'Sorcery',
        url:'SorceryAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'71',
        level: 1,
        type: 'Sorcery',
        url:'SorceryBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'72',
        level: 3,
        type: 'Sorcery',
        url:'SorceryExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'73',
        level: 2,
        type: 'Tactics',
        url:'TacticsAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'74',
        level: 1,
        type: 'Tactics',
        url:'TacticsBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'75',
        level: 3,
        type: 'Tactics',
        url:'TacticsExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'76',
        level: 2,
        type: 'WaterMagic',
        url:'WaterMagicAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'77',
        level: 1,
        type: 'WaterMagic',
        url:'WaterMagicBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'78',
        level: 3,
        type: 'WaterMagic',
        url:'WaterMagicExpert.jpg',
        title:'88',
        width:'',
    },

    {
        id:'79',
        level: 2,
        type: 'Wisdom',
        url:'WisdomAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'80',
        level: 1,
        type: 'Wisdom',
        url:'WisdomBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'81',
        level: 3,
        type: 'Wisdom',
        url:'WisdomExpert.jpg',
        title:'88',
        width:'',
    },
    {
        id:'82',
        level: 2,
        type: 'Scholar',
        url:'ScholarAdvanced.jpg',
        title:'89',
        width:'',
    },
    {
        id:'83',
        level: 1,
        type: 'Scholar',
        url:'ScholarBasic.jpg',
        title:'98',
        width:'',
    },
    {
        id:'84',
        level: 3,
        type: 'Scholar',
        url:'ScholarExpert.jpg',
        title:'88',
        width:'',
    },

]

export let getAll = ():SkillImageModel[] => {
    return images
}

export const getById = (id:string):SkillImageModel => {
    let result = images.find(x=>x.id==id)
    if(!result){
        result = images[0];
    }
    return result
}

export const getSameForOtherLevel = (id:string, isUp:boolean):SkillImageModel => {
    const image = images.filter(x=>x.id===id)[0]
    const resultImages = images.filter(x=>x.type===image.type)
    if(isUp){
         const imageResult =  resultImages.filter(x=>x.level-1===image.level)[0]
        return imageResult
    }
    const imageResult =  resultImages.filter(x=>x.level+1===image.level)[0]
        return imageResult
}

export const getRandomImage = (existingTypes: string []):SkillImageModel =>{
    const notExistingImages = images.filter(x=> {
        if(!existingTypes.includes(x.type)){
            return x
        }
    })

    const firstLevelSkill = notExistingImages.filter(x=>x.level===1)
    const randomImageNumber = getRandomInt(firstLevelSkill.length)
    const randomImage = firstLevelSkill[randomImageNumber]
    return randomImage
}

export let getByType = (type:string):SkillImageModel[] => {
    const result = images.filter(x=>x.type===type)
    return result
}

let  getRandomInt = (max: number) => {
    return Math.floor(Math.random() * max);
  }
